// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxdgguydbsxojushpfqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZGdndXlkYnN4b2p1c2hwZnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjEyNDMsImV4cCI6MjA2NjI5NzI0M30.XHGP_fzTikj466OSdJSSUrxPLknlk7ZZcV-oY-pBLsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);